{
 "title": "Shelly4b",
 "time": { "from": "2021-02-05T07:38:01.912Z", "to": "2021-02-05T07:41:35.351Z" },
 "panels": [
  {
   "title": "Relay Total Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(shelly4b_relay_meter_total/60)"
    }
   ]
  },
  {
   "title": "Relay Total Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(shelly4b_relay_meter_power)"
    }
   ]
  },
  {
   "title": "Relay Power Draw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "shelly4b_relay_meter_power" }
   ]
  }
 ]
}